### ISSUE TITLE
Shift + click outside the inventory with items in the cursor to drop all matching items from the entire inventory

### ISSUE THREAD

**Issue by mrGRINCH** [TwelveIterationMods/InventoryEssentials#17]
These are taken directly from Item Scroller, but Item Scroller isn't available for Forge unfortunately.

Shift + click outside the inventory with items in the cursor: Drop all matching items from the entire inventory.
Alt + shift + click: Move everything to or from the other inventory.

**Comment by BlayTheNinth** [comment]
Moving everything already exists via Space + Click. Configurable key bindings are planned in #11

**Comment by mrGRINCH** [comment]
Any chance of adding the click drag to drop all matching?
